# librerias curso

install.packages("geoR")
install.packages("spdep")
install.packages("sp")
install.packages("gstat")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("terra")
install.packages("sf")
install.packages("dplyr")
install.packages('stars')
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
install.packages("remotes")
install_github("r-tmap/tmaptools")
install_github("r-tmap/tmap")
##
library(geoR)
library(INLA)
library(spdep)
library(sp)
library(gstat)
library(tidyverse)
library(ggplot2)
library(stars)
library(sf)
library(terra)
library(tmap)# esta cambiando la version
library(remotes)

